//로그인 액션 타입
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
//회원가입 액션 타입
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

//로그인 세션 확인 구현/로그아웃 구현

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

//로그아웃
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//POST
export const IMAGE_POST = "IMAGE_POST";
export const IMAGE_POST_SUCCESS = "IMAGE_POST_SUCCESS";
export const IMAGE_POST_FAILURE = "IMAGE_POST_FAILURE";
